@startuml
title Diagrama de Sequencia referente ao CDU001 - Listar todas as Tarefas
actor Usuário
Boundary Frontend
Boundary SpringBoot
Control TaskController
Entity Task
Participant TaskService
Participant TaskRepository
Participant pagedResourcesAssembler
Boundary TypedQuery
Participant Hibernate
Database TodoList
activate SpringBoot
Usuário -> Frontend: Listar Tarefas
activate Usuário
activate Frontend
activate TodoList
Frontend -> SpringBoot: GET api/tasks/
group Roteiro01Application [Spring Boot Java Application]
SpringBoot -> TaskController: listAll(TaskDto, Pageable, PersistentEntityResourceAssembler)
activate TaskController
TaskController -> TaskService: listAll(pageable)
activate TaskService
TaskService -> TaskRepository: findAll(pageable)
activate TaskRepository
TaskRepository -> TypedQuery: getResultList(TaskDto)
group JPA Framework[Hibernate]
Activate TypedQuery
TypedQuery -> Hibernate: List(TaskDto)
Activate Hibernate
Hibernate -> TodoList: SELECT * FROM Tasks
TodoList --> Hibernate: Table Tasks
Hibernate --> TypedQuery: Table Tasks
TypedQuery --> TaskRepository: Page<Tasks>
destroy TypedQuery
end
TaskRepository --> TaskService: Page<Task>
destroy TaskRepository
TaskService -->TaskController: Page<Task> events
destroy TaskService
TaskController -> pagedResourcesAssembler: toModel(events, resourceAssembler)
activate pagedResourcesAssembler
pagedResourcesAssembler --> TaskController: PagedModel<Task> resource
destroy pagedResourcesAssembler
TaskController --> SpringBoot: ResponseEntity<Task> ResponseEntity.ok(resource)
destroy TaskController
end
SpringBoot --> Frontend : ResponseEntity<Task> ResponseEntity.ok(resource)
Frontend --> Usuário: <list>Task
@enduml