@startuml
title Diagrama de Sequencia referente ao CDU004 - CONCLUIR TAREFA
actor Usuário
Boundary Frontend
Boundary SpringBoot
Control TaskController
Entity Task
Participant TaskService
Participant TaskRepository
Participant pagedResourcesAssembler
Boundary TypedQuery
Participant Hibernate
Database TodoList
activate SpringBoot
Usuário -> Frontend: CONCLUIR TAREFA
activate Usuário
activate Frontend
activate TodoList
Frontend -> SpringBoot: PUT tasks/{id}/conclude
group Roteiro01Application [Spring Boot Java Application]
SpringBoot -> TaskController: concludeTask(Long)
activate TaskController
TaskController -> TaskService: concludeTask(Long)
activate TaskService
TaskService -> TaskRepository: concludeTask(Long)
activate TaskRepository
TaskRepository -> TypedQuery: getResult(Long)
group JPA Framework[Hibernate]
Activate TypedQuery
TypedQuery -> Hibernate: Object Task
Activate Hibernate
Hibernate -> TodoList: UPDATE tasks SET (status='concluido') WHERE id_task = id
TodoList --> Hibernate: Table Tasks
Hibernate --> TypedQuery: Table Tasks
TypedQuery --> TaskRepository: Page<Tasks>
destroy TypedQuery
end
TaskRepository --> TaskService: Page<Task>
destroy TaskRepository
TaskService -->TaskController: Page<Task> events
destroy TaskService
TaskController -> pagedResourcesAssembler: toModel(events, resourceAssembler)
activate pagedResourcesAssembler
pagedResourcesAssembler --> TaskController: PagedModel<Task> resource
destroy pagedResourcesAssembler
TaskController --> SpringBoot: ResponseEntity<Task> ResponseEntity.ok(resource)
destroy TaskController
end
SpringBoot --> Frontend : ResponseEntity<Task> ResponseEntity.ok(resource)
Frontend --> Usuário: <list>Task
@enduml